spring.application.name=tiendaOnline

# ============= DEVELOP ================
# spring.datasource.url=jdbc:postgresql://localhost:5432/tiendaOnline
# spring.datasource.username=postgres
# spring.datasource.password=02072013

# ============= DEPLOYMENT ================
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USER}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=xandersoftworks@gmail.com
spring.mail.password=ruvz ggxm duam pcla
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload-dir=src/main/resources/static/uploads

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

imagen.perfil.por.defecto=/images/sinImagenPerfil.webp

server.port=${PORT:8080}